dna_seq = 'TCTTCACTGTTACTCCTGTGAGATGGGTACCGAAGAAGTGAATCTGTCCGGTTCTCTGTATGGTCTATCTTCAATCACCATCCTAGTATCCCACATTCATAATTGGTGGGAAGTCTTGCAGACTACTCGGGCGTCGATTAAGGAACTGTACATGAGCAGATGAGGAATCATTGTGGCAAACGTCTCGCTGTGCGGACAGGGCAATATCAATAGGCCTCTTTTCCATCCCCTGACCCCTCCCGTCTTGCTCTCCACGCCACGTAGGTACCTGGGCAAAAAACATGCTTGCGTAAATAATTACCGTTAGACCTACTGGCCTCAAATGCGATGATAAGCCGAGTATGATGGCCAGATGACGATGAGATACTCGTTCGCCGAGAACTGCATACAGGTTGTGTTCAAGTGGCATGTCATTCATAGGCTCGTAAACATGCAATATTTGTTACGAACCGCATTGCTCGTTTAGCGTCGATCCACTAACCGGAGCGTAGTCTTATGACGGACTTGTCGTTATAGAATGCCTGTACTGAACCACCTAAACAGGTGGAATCACTTCCACAGCCATTATGCACTGCTGGATTTACCGAAAGCTACGGTGCAACCGTTCGGATTAGACGAGTACTGATCACGTAGTGCGGGATCGACGTACCGGTTCTTTGGGTGCTTTAGGCATGGCTCGGACCCTCCATTACGTCATACTTGGCTTTACCATGCCTGTCTACATATAGGACATACTTACGGGTACTACGAATTAGTTGGCCCCATCCGAGATGGAATACCAGAATCTCGCTATATTTAAGAACTGCACCATCGAGCCCCGAATGGCTTCATGGTTGTCAGGCCCATCACATGGTCATCC'

list = []
for bp in dna_seq:
    list.append(bp)

for i in range(len(list)):
    if list[i] == 'A':
        list[i] = 'T'
    elif list[i] == 'C':
        list[i] = 'G'
    elif list[i] == 'T':
        list[i] = 'A'
    elif list[i] == 'G':
        list[i] = 'C'

list.reverse()
output = "".join(list)

print(output)
